
-- add table user_siswa 

CREATE TABLE public.user_siswa (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NOT NULL,
	"name" varchar(255) NULL,
	"password" varchar(255) NULL,
	grade varchar(255) NULL,
	major varchar(255) NULL,
	CONSTRAINT ukf47qj8e3r87uostj2nqvrweef UNIQUE (email),
	CONSTRAINT user_siswa_pkey PRIMARY KEY (id)
);

--add table subject 

CREATE TABLE public.subject (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	grade varchar(255) NULL,
	major varchar(255) NULL,
	subject_name varchar(255) NULL,
	CONSTRAINT subject_pkey PRIMARY KEY (id)
);

-- add table user_subject 

CREATE TABLE public.user_subject (
	user_id int8 NOT NULL,
	subject_id int8 NOT NULL
);


-- public.user_subject foreign keys

ALTER TABLE public.user_subject ADD CONSTRAINT fk8xwdo7i5lavkapi3hf891raea FOREIGN KEY (subject_id) REFERENCES public.subject(id);
ALTER TABLE public.user_subject ADD CONSTRAINT fkthjecoa1ugbnjspqhh1irxioi FOREIGN KEY (user_id) REFERENCES public.user_siswa(id);